package com.jme3.shader.uniformValue;

public enum EnumVarType {
	MATRIX3, MATRIX4, INTARRAY, FLOATARRAY, VECTOR2ARRAY, VECTOR3ARRAY, 
	VECTOR4ARRAY, MATRIX3ARRAY, MATRIX4ARRAY, VECTOR2, VECTOR3, 
	VECTOR4, INT, FLOAT, BOOLEAN, DEFAULT
}
